// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Integracion.Esquemas.Referencias
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Contrato : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""Contrato"",""namespace"":""Integracion.Esquemas.Referencias"",""fields"":[{""name"":""codigoDeContratoInterno"",""type"":""string""},{""name"":""descripcion"",""default"":null,""type"":[""null"",""string""]},{""name"":""estaActivo"",""type"":""boolean""},{""name"":""tipoDeServicio"",""default"":null,""type"":[""null"",""string""]},{""name"":""codigoDeDireccion"",""default"":null,""type"":[""null"",""string""]},{""name"":""codigoDeClienteInterno"",""type"":""string""},{""name"":""vigenciaDesde"",""default"":null,""type"":[""null"",""string""]},{""name"":""vigenciaHasta"",""default"":null,""type"":[""null"",""string""]}]}");
		private string _codigoDeContratoInterno;
		private string _descripcion;
		private bool _estaActivo;
		private string _tipoDeServicio;
		private string _codigoDeDireccion;
		private string _codigoDeClienteInterno;
		private string _vigenciaDesde;
		private string _vigenciaHasta;
		public virtual Schema Schema
		{
			get
			{
				return Contrato._SCHEMA;
			}
		}
		public string codigoDeContratoInterno
		{
			get
			{
				return this._codigoDeContratoInterno;
			}
			set
			{
				this._codigoDeContratoInterno = value;
			}
		}
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				this._descripcion = value;
			}
		}
		public bool estaActivo
		{
			get
			{
				return this._estaActivo;
			}
			set
			{
				this._estaActivo = value;
			}
		}
		public string tipoDeServicio
		{
			get
			{
				return this._tipoDeServicio;
			}
			set
			{
				this._tipoDeServicio = value;
			}
		}
		public string codigoDeDireccion
		{
			get
			{
				return this._codigoDeDireccion;
			}
			set
			{
				this._codigoDeDireccion = value;
			}
		}
		public string codigoDeClienteInterno
		{
			get
			{
				return this._codigoDeClienteInterno;
			}
			set
			{
				this._codigoDeClienteInterno = value;
			}
		}
		public string vigenciaDesde
		{
			get
			{
				return this._vigenciaDesde;
			}
			set
			{
				this._vigenciaDesde = value;
			}
		}
		public string vigenciaHasta
		{
			get
			{
				return this._vigenciaHasta;
			}
			set
			{
				this._vigenciaHasta = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.codigoDeContratoInterno;
			case 1: return this.descripcion;
			case 2: return this.estaActivo;
			case 3: return this.tipoDeServicio;
			case 4: return this.codigoDeDireccion;
			case 5: return this.codigoDeClienteInterno;
			case 6: return this.vigenciaDesde;
			case 7: return this.vigenciaHasta;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.codigoDeContratoInterno = (System.String)fieldValue; break;
			case 1: this.descripcion = (System.String)fieldValue; break;
			case 2: this.estaActivo = (System.Boolean)fieldValue; break;
			case 3: this.tipoDeServicio = (System.String)fieldValue; break;
			case 4: this.codigoDeDireccion = (System.String)fieldValue; break;
			case 5: this.codigoDeClienteInterno = (System.String)fieldValue; break;
			case 6: this.vigenciaDesde = (System.String)fieldValue; break;
			case 7: this.vigenciaHasta = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
