// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Integracion.Esquemas.Referencias
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class DatosPersonales : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""DatosPersonales"",""namespace"":""Integracion.Esquemas.Referencias"",""fields"":[{""name"":""numeroDeDocumento"",""default"":null,""type"":[""null"",""string""]},{""name"":""nombreCompleto"",""default"":null,""type"":[""null"",""string""]},{""name"":""idInternoDelCliente"",""default"":null,""type"":[""null"",""string""]},{""name"":""eMail"",""default"":null,""type"":[""null"",""string""]},{""name"":""telefonos"",""default"":null,""type"":[""null"",{""type"":""array"",""items"":{""type"":""record"",""name"":""Telefono"",""namespace"":""Integracion.Esquemas.Referencias"",""fields"":[{""name"":""tipo"",""type"":{""type"":""enum"",""name"":""TipoDeTelefono"",""namespace"":""Integracion.Esquemas.Referencias"",""symbols"":[""trabajo"",""celular"",""casa"",""otro""]}},{""name"":""numero"",""type"":""string""}]}}]},{""name"":""agrupador"",""default"":null,""type"":[""null"",""string""]},{""name"":""tipoDeDocumento"",""type"":{""type"":""enum"",""name"":""TipoDeDocumento"",""namespace"":""Integracion.Esquemas.Referencias"",""symbols"":[""undefined"",""DNI"",""CUIT"",""CUIL""]}}]}");
		private string _numeroDeDocumento;
		private string _nombreCompleto;
		private string _idInternoDelCliente;
		private string _eMail;
		private IList<Integracion.Esquemas.Referencias.Telefono> _telefonos;
		private string _agrupador;
		private Integracion.Esquemas.Referencias.TipoDeDocumento _tipoDeDocumento;
		public virtual Schema Schema
		{
			get
			{
				return DatosPersonales._SCHEMA;
			}
		}
		public string numeroDeDocumento
		{
			get
			{
				return this._numeroDeDocumento;
			}
			set
			{
				this._numeroDeDocumento = value;
			}
		}
		public string nombreCompleto
		{
			get
			{
				return this._nombreCompleto;
			}
			set
			{
				this._nombreCompleto = value;
			}
		}
		public string idInternoDelCliente
		{
			get
			{
				return this._idInternoDelCliente;
			}
			set
			{
				this._idInternoDelCliente = value;
			}
		}
		public string eMail
		{
			get
			{
				return this._eMail;
			}
			set
			{
				this._eMail = value;
			}
		}
		public IList<Integracion.Esquemas.Referencias.Telefono> telefonos
		{
			get
			{
				return this._telefonos;
			}
			set
			{
				this._telefonos = value;
			}
		}
		public string agrupador
		{
			get
			{
				return this._agrupador;
			}
			set
			{
				this._agrupador = value;
			}
		}
		public Integracion.Esquemas.Referencias.TipoDeDocumento tipoDeDocumento
		{
			get
			{
				return this._tipoDeDocumento;
			}
			set
			{
				this._tipoDeDocumento = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.numeroDeDocumento;
			case 1: return this.nombreCompleto;
			case 2: return this.idInternoDelCliente;
			case 3: return this.eMail;
			case 4: return this.telefonos;
			case 5: return this.agrupador;
			case 6: return this.tipoDeDocumento;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.numeroDeDocumento = (System.String)fieldValue; break;
			case 1: this.nombreCompleto = (System.String)fieldValue; break;
			case 2: this.idInternoDelCliente = (System.String)fieldValue; break;
			case 3: this.eMail = (System.String)fieldValue; break;
			case 4: this.telefonos = (IList<Integracion.Esquemas.Referencias.Telefono>)fieldValue; break;
			case 5: this.agrupador = (System.String)fieldValue; break;
			case 6: this.tipoDeDocumento = (Integracion.Esquemas.Referencias.TipoDeDocumento)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
