// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Integracion.Esquemas.Referencias
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class DetalleDeEnvio : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"DetalleDeEnvio\",\"namespace\":\"Integracion.Esquemas.Refere" +
				"ncias\",\"fields\":[{\"name\":\"fechaDeRecibo\",\"default\":null,\"type\":[\"null\",\"string\"]" +
				"},{\"name\":\"informaTarifa\",\"type\":\"boolean\"},{\"name\":\"lote\",\"default\":null,\"type\"" +
				":[\"null\",\"string\"]},{\"name\":\"numeroDeEnvio\",\"type\":\"string\"},{\"name\":\"numeroDeRe" +
				"cibo\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"numeroInformeDeRendicion" +
				"\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"peso\",\"default\":null,\"type\":" +
				"[\"null\",\"float\"]},{\"name\":\"pesoAforado\",\"default\":null,\"type\":[\"null\",\"float\"]}," +
				"{\"name\":\"valorDeclarado\",\"default\":null,\"type\":[\"null\",\"float\"]},{\"name\":\"valorA" +
				"Cobrar\",\"default\":null,\"type\":[\"null\",\"float\"]},{\"name\":\"volumen\",\"default\":null" +
				",\"type\":[\"null\",\"float\"]},{\"name\":\"origen\",\"default\":null,\"type\":[\"null\",{\"type\"" +
				":\"record\",\"name\":\"LugarDeRetiroEntrega\",\"namespace\":\"Integracion.Esquemas.Refere" +
				"ncias\",\"fields\":[{\"name\":\"datosSucursal\",\"default\":null,\"type\":[\"null\",{\"type\":\"" +
				"record\",\"name\":\"DatosSucursal\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"f" +
				"ields\":[{\"name\":\"codigo\",\"type\":\"string\"},{\"name\":\"nombre\",\"default\":null,\"type\"" +
				":[\"null\",\"string\"]},{\"name\":\"id\",\"type\":\"string\"}]}]},{\"name\":\"domicilio\",\"defau" +
				"lt\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Direccion\",\"namespace\":\"Integra" +
				"cion.Esquemas.Referencias\",\"fields\":[{\"name\":\"abreviaturaProvincia\",\"default\":nu" +
				"ll,\"type\":[\"null\",\"string\"]},{\"name\":\"calle\",\"default\":null,\"type\":[\"null\",\"stri" +
				"ng\"]},{\"name\":\"codigoDeDireccion\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"nam" +
				"e\":\"codigoCiudad\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"codigoPostal" +
				"\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"nombreProvincia\",\"default\":n" +
				"ull,\"type\":[\"null\",\"string\"]},{\"name\":\"numero\",\"default\":null,\"type\":[\"null\",\"st" +
				"ring\"]},{\"name\":\"telefono\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"cod" +
				"igoISOProvincia\",\"doc\":\"segun ISO -3166-2 (https://es.wikipedia.org/wiki/ISO_316" +
				"6-2:AR)\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"codigoISOPais\",\"doc\":" +
				"\"segun ISO 3166-1 alpha-2 (https://es.wikipedia.org/wiki/ISO_3166-1#Tabla_de_c.C" +
				"3.B3digos_alfa-2_asignados_o_reservados)\",\"default\":null,\"type\":[\"null\",\"string\"" +
				"]},{\"name\":\"localidad\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"compone" +
				"ntesDeDireccion\",\"default\":null,\"type\":[\"null\",{\"type\":\"map\",\"values\":\"string\"}]" +
				"},{\"name\":\"coordenadas\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"G" +
				"eoReferencia\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"fields\":[{\"name\":\"" +
				"latitud\",\"default\":null,\"type\":[\"null\",\"double\"]},{\"name\":\"longitud\",\"default\":n" +
				"ull,\"type\":[\"null\",\"double\"]},{\"name\":\"altura\",\"default\":null,\"type\":[\"null\",\"do" +
				"uble\"]}]}]}]}]}]}]},{\"name\":\"sucursalOrigen\",\"default\":null,\"type\":[\"null\",\"Luga" +
				"rDeRetiroEntrega\"]},{\"name\":\"destino\",\"type\":\"LugarDeRetiroEntrega\"},{\"name\":\"su" +
				"cursalDestino\",\"default\":null,\"type\":[\"null\",\"LugarDeRetiroEntrega\"]},{\"name\":\"c" +
				"ategoriaDeFacturacion\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"centroD" +
				"eCostosDelCliente\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"estado\",\"ty" +
				"pe\":\"string\"},{\"name\":\"codigoDeContratoInterno\",\"type\":\"string\"},{\"name\":\"fechaI" +
				"nformeDeRendicion\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"fechaAltaEn" +
				"vio\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"ordenDeCompraCliente\",\"de" +
				"fault\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"tarifa\",\"default\":null,\"type\":[\"n" +
				"ull\",\"double\"]},{\"name\":\"componentes\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"re" +
				"cord\",\"name\":\"DatosPersonales\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"f" +
				"ields\":[{\"name\":\"numeroDeDocumento\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"n" +
				"ame\":\"nombreCompleto\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"idIntern" +
				"oDelCliente\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"eMail\",\"default\":" +
				"null,\"type\":[\"null\",\"string\"]},{\"name\":\"telefonos\",\"default\":null,\"type\":[\"null\"" +
				",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Telefono\",\"namespace\":\"Integra" +
				"cion.Esquemas.Referencias\",\"fields\":[{\"name\":\"tipo\",\"type\":{\"type\":\"enum\",\"name\"" +
				":\"TipoDeTelefono\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"symbols\":[\"tra" +
				"bajo\",\"celular\",\"casa\",\"otro\"]}},{\"name\":\"numero\",\"type\":\"string\"}]}}]},{\"name\":" +
				"\"agrupador\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"tipoDeDocumento\",\"" +
				"type\":{\"type\":\"enum\",\"name\":\"TipoDeDocumento\",\"namespace\":\"Integracion.Esquemas." +
				"Referencias\",\"symbols\":[\"undefined\",\"DNI\",\"CUIT\",\"CUIL\"]}}]}}},{\"name\":\"destinat" +
				"ario\",\"default\":null,\"type\":[\"null\",\"DatosPersonales\"]},{\"name\":\"remitente\",\"def" +
				"ault\":null,\"type\":[\"null\",\"DatosPersonales\"]},{\"name\":\"cantidadDeBultos\",\"defaul" +
				"t\":null,\"type\":[\"null\",\"int\"]},{\"name\":\"fechaProbableDeEntrega\",\"default\":null,\"" +
				"type\":[\"null\",\"string\"]},{\"name\":\"observaciones\",\"default\":null,\"type\":[\"null\",\"" +
				"string\"]},{\"name\":\"numeroDeRemito\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"na" +
				"me\":\"numeroDeSeguimientoDelCliente\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"n" +
				"ame\":\"datosAdicionales\",\"default\":null,\"type\":[\"null\",{\"type\":\"map\",\"values\":\"st" +
				"ring\"}]},{\"name\":\"fechaPactadaDeEntrega\",\"default\":null,\"type\":[\"null\",\"string\"]" +
				"},{\"name\":\"altoEnCm\",\"default\":null,\"type\":[\"null\",\"double\"]},{\"name\":\"anchoEnCm" +
				"\",\"default\":null,\"type\":[\"null\",\"double\"]},{\"name\":\"largoEnCm\",\"default\":null,\"t" +
				"ype\":[\"null\",\"double\"]}]}");
		private string _fechaDeRecibo;
		private bool _informaTarifa;
		private string _lote;
		private string _numeroDeEnvio;
		private string _numeroDeRecibo;
		private string _numeroInformeDeRendicion;
		private System.Nullable<System.Single> _peso;
		private System.Nullable<System.Single> _pesoAforado;
		private System.Nullable<System.Single> _valorDeclarado;
		private System.Nullable<System.Single> _valorACobrar;
		private System.Nullable<System.Single> _volumen;
		private Integracion.Esquemas.Referencias.LugarDeRetiroEntrega _origen;
		private Integracion.Esquemas.Referencias.LugarDeRetiroEntrega _sucursalOrigen;
		private Integracion.Esquemas.Referencias.LugarDeRetiroEntrega _destino;
		private Integracion.Esquemas.Referencias.LugarDeRetiroEntrega _sucursalDestino;
		private string _categoriaDeFacturacion;
		private string _centroDeCostosDelCliente;
		private string _estado;
		private string _codigoDeContratoInterno;
		private string _fechaInformeDeRendicion;
		private string _fechaAltaEnvio;
		private string _ordenDeCompraCliente;
		private System.Nullable<System.Double> _tarifa;
		private IList<Integracion.Esquemas.Referencias.DatosPersonales> _componentes;
		private Integracion.Esquemas.Referencias.DatosPersonales _destinatario;
		private Integracion.Esquemas.Referencias.DatosPersonales _remitente;
		private System.Nullable<System.Int32> _cantidadDeBultos;
		private string _fechaProbableDeEntrega;
		private string _observaciones;
		private string _numeroDeRemito;
		private string _numeroDeSeguimientoDelCliente;
		private IDictionary<string,System.String> _datosAdicionales;
		private string _fechaPactadaDeEntrega;
		private System.Nullable<System.Double> _altoEnCm;
		private System.Nullable<System.Double> _anchoEnCm;
		private System.Nullable<System.Double> _largoEnCm;
		public virtual Schema Schema
		{
			get
			{
				return DetalleDeEnvio._SCHEMA;
			}
		}
		public string fechaDeRecibo
		{
			get
			{
				return this._fechaDeRecibo;
			}
			set
			{
				this._fechaDeRecibo = value;
			}
		}
		public bool informaTarifa
		{
			get
			{
				return this._informaTarifa;
			}
			set
			{
				this._informaTarifa = value;
			}
		}
		public string lote
		{
			get
			{
				return this._lote;
			}
			set
			{
				this._lote = value;
			}
		}
		public string numeroDeEnvio
		{
			get
			{
				return this._numeroDeEnvio;
			}
			set
			{
				this._numeroDeEnvio = value;
			}
		}
		public string numeroDeRecibo
		{
			get
			{
				return this._numeroDeRecibo;
			}
			set
			{
				this._numeroDeRecibo = value;
			}
		}
		public string numeroInformeDeRendicion
		{
			get
			{
				return this._numeroInformeDeRendicion;
			}
			set
			{
				this._numeroInformeDeRendicion = value;
			}
		}
		public System.Nullable<System.Single> peso
		{
			get
			{
				return this._peso;
			}
			set
			{
				this._peso = value;
			}
		}
		public System.Nullable<System.Single> pesoAforado
		{
			get
			{
				return this._pesoAforado;
			}
			set
			{
				this._pesoAforado = value;
			}
		}
		public System.Nullable<System.Single> valorDeclarado
		{
			get
			{
				return this._valorDeclarado;
			}
			set
			{
				this._valorDeclarado = value;
			}
		}
		public System.Nullable<System.Single> valorACobrar
		{
			get
			{
				return this._valorACobrar;
			}
			set
			{
				this._valorACobrar = value;
			}
		}
		public System.Nullable<System.Single> volumen
		{
			get
			{
				return this._volumen;
			}
			set
			{
				this._volumen = value;
			}
		}
		public Integracion.Esquemas.Referencias.LugarDeRetiroEntrega origen
		{
			get
			{
				return this._origen;
			}
			set
			{
				this._origen = value;
			}
		}
		public Integracion.Esquemas.Referencias.LugarDeRetiroEntrega sucursalOrigen
		{
			get
			{
				return this._sucursalOrigen;
			}
			set
			{
				this._sucursalOrigen = value;
			}
		}
		public Integracion.Esquemas.Referencias.LugarDeRetiroEntrega destino
		{
			get
			{
				return this._destino;
			}
			set
			{
				this._destino = value;
			}
		}
		public Integracion.Esquemas.Referencias.LugarDeRetiroEntrega sucursalDestino
		{
			get
			{
				return this._sucursalDestino;
			}
			set
			{
				this._sucursalDestino = value;
			}
		}
		public string categoriaDeFacturacion
		{
			get
			{
				return this._categoriaDeFacturacion;
			}
			set
			{
				this._categoriaDeFacturacion = value;
			}
		}
		public string centroDeCostosDelCliente
		{
			get
			{
				return this._centroDeCostosDelCliente;
			}
			set
			{
				this._centroDeCostosDelCliente = value;
			}
		}
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				this._estado = value;
			}
		}
		public string codigoDeContratoInterno
		{
			get
			{
				return this._codigoDeContratoInterno;
			}
			set
			{
				this._codigoDeContratoInterno = value;
			}
		}
		public string fechaInformeDeRendicion
		{
			get
			{
				return this._fechaInformeDeRendicion;
			}
			set
			{
				this._fechaInformeDeRendicion = value;
			}
		}
		public string fechaAltaEnvio
		{
			get
			{
				return this._fechaAltaEnvio;
			}
			set
			{
				this._fechaAltaEnvio = value;
			}
		}
		public string ordenDeCompraCliente
		{
			get
			{
				return this._ordenDeCompraCliente;
			}
			set
			{
				this._ordenDeCompraCliente = value;
			}
		}
		public System.Nullable<System.Double> tarifa
		{
			get
			{
				return this._tarifa;
			}
			set
			{
				this._tarifa = value;
			}
		}
		public IList<Integracion.Esquemas.Referencias.DatosPersonales> componentes
		{
			get
			{
				return this._componentes;
			}
			set
			{
				this._componentes = value;
			}
		}
		public Integracion.Esquemas.Referencias.DatosPersonales destinatario
		{
			get
			{
				return this._destinatario;
			}
			set
			{
				this._destinatario = value;
			}
		}
		public Integracion.Esquemas.Referencias.DatosPersonales remitente
		{
			get
			{
				return this._remitente;
			}
			set
			{
				this._remitente = value;
			}
		}
		public System.Nullable<System.Int32> cantidadDeBultos
		{
			get
			{
				return this._cantidadDeBultos;
			}
			set
			{
				this._cantidadDeBultos = value;
			}
		}
		public string fechaProbableDeEntrega
		{
			get
			{
				return this._fechaProbableDeEntrega;
			}
			set
			{
				this._fechaProbableDeEntrega = value;
			}
		}
		public string observaciones
		{
			get
			{
				return this._observaciones;
			}
			set
			{
				this._observaciones = value;
			}
		}
		public string numeroDeRemito
		{
			get
			{
				return this._numeroDeRemito;
			}
			set
			{
				this._numeroDeRemito = value;
			}
		}
		public string numeroDeSeguimientoDelCliente
		{
			get
			{
				return this._numeroDeSeguimientoDelCliente;
			}
			set
			{
				this._numeroDeSeguimientoDelCliente = value;
			}
		}
		public IDictionary<string,System.String> datosAdicionales
		{
			get
			{
				return this._datosAdicionales;
			}
			set
			{
				this._datosAdicionales = value;
			}
		}
		public string fechaPactadaDeEntrega
		{
			get
			{
				return this._fechaPactadaDeEntrega;
			}
			set
			{
				this._fechaPactadaDeEntrega = value;
			}
		}
		public System.Nullable<System.Double> altoEnCm
		{
			get
			{
				return this._altoEnCm;
			}
			set
			{
				this._altoEnCm = value;
			}
		}
		public System.Nullable<System.Double> anchoEnCm
		{
			get
			{
				return this._anchoEnCm;
			}
			set
			{
				this._anchoEnCm = value;
			}
		}
		public System.Nullable<System.Double> largoEnCm
		{
			get
			{
				return this._largoEnCm;
			}
			set
			{
				this._largoEnCm = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.fechaDeRecibo;
			case 1: return this.informaTarifa;
			case 2: return this.lote;
			case 3: return this.numeroDeEnvio;
			case 4: return this.numeroDeRecibo;
			case 5: return this.numeroInformeDeRendicion;
			case 6: return this.peso;
			case 7: return this.pesoAforado;
			case 8: return this.valorDeclarado;
			case 9: return this.valorACobrar;
			case 10: return this.volumen;
			case 11: return this.origen;
			case 12: return this.sucursalOrigen;
			case 13: return this.destino;
			case 14: return this.sucursalDestino;
			case 15: return this.categoriaDeFacturacion;
			case 16: return this.centroDeCostosDelCliente;
			case 17: return this.estado;
			case 18: return this.codigoDeContratoInterno;
			case 19: return this.fechaInformeDeRendicion;
			case 20: return this.fechaAltaEnvio;
			case 21: return this.ordenDeCompraCliente;
			case 22: return this.tarifa;
			case 23: return this.componentes;
			case 24: return this.destinatario;
			case 25: return this.remitente;
			case 26: return this.cantidadDeBultos;
			case 27: return this.fechaProbableDeEntrega;
			case 28: return this.observaciones;
			case 29: return this.numeroDeRemito;
			case 30: return this.numeroDeSeguimientoDelCliente;
			case 31: return this.datosAdicionales;
			case 32: return this.fechaPactadaDeEntrega;
			case 33: return this.altoEnCm;
			case 34: return this.anchoEnCm;
			case 35: return this.largoEnCm;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.fechaDeRecibo = (System.String)fieldValue; break;
			case 1: this.informaTarifa = (System.Boolean)fieldValue; break;
			case 2: this.lote = (System.String)fieldValue; break;
			case 3: this.numeroDeEnvio = (System.String)fieldValue; break;
			case 4: this.numeroDeRecibo = (System.String)fieldValue; break;
			case 5: this.numeroInformeDeRendicion = (System.String)fieldValue; break;
			case 6: this.peso = (System.Nullable<System.Single>)fieldValue; break;
			case 7: this.pesoAforado = (System.Nullable<System.Single>)fieldValue; break;
			case 8: this.valorDeclarado = (System.Nullable<System.Single>)fieldValue; break;
			case 9: this.valorACobrar = (System.Nullable<System.Single>)fieldValue; break;
			case 10: this.volumen = (System.Nullable<System.Single>)fieldValue; break;
			case 11: this.origen = (Integracion.Esquemas.Referencias.LugarDeRetiroEntrega)fieldValue; break;
			case 12: this.sucursalOrigen = (Integracion.Esquemas.Referencias.LugarDeRetiroEntrega)fieldValue; break;
			case 13: this.destino = (Integracion.Esquemas.Referencias.LugarDeRetiroEntrega)fieldValue; break;
			case 14: this.sucursalDestino = (Integracion.Esquemas.Referencias.LugarDeRetiroEntrega)fieldValue; break;
			case 15: this.categoriaDeFacturacion = (System.String)fieldValue; break;
			case 16: this.centroDeCostosDelCliente = (System.String)fieldValue; break;
			case 17: this.estado = (System.String)fieldValue; break;
			case 18: this.codigoDeContratoInterno = (System.String)fieldValue; break;
			case 19: this.fechaInformeDeRendicion = (System.String)fieldValue; break;
			case 20: this.fechaAltaEnvio = (System.String)fieldValue; break;
			case 21: this.ordenDeCompraCliente = (System.String)fieldValue; break;
			case 22: this.tarifa = (System.Nullable<System.Double>)fieldValue; break;
			case 23: this.componentes = (IList<Integracion.Esquemas.Referencias.DatosPersonales>)fieldValue; break;
			case 24: this.destinatario = (Integracion.Esquemas.Referencias.DatosPersonales)fieldValue; break;
			case 25: this.remitente = (Integracion.Esquemas.Referencias.DatosPersonales)fieldValue; break;
			case 26: this.cantidadDeBultos = (System.Nullable<System.Int32>)fieldValue; break;
			case 27: this.fechaProbableDeEntrega = (System.String)fieldValue; break;
			case 28: this.observaciones = (System.String)fieldValue; break;
			case 29: this.numeroDeRemito = (System.String)fieldValue; break;
			case 30: this.numeroDeSeguimientoDelCliente = (System.String)fieldValue; break;
			case 31: this.datosAdicionales = (IDictionary<string,System.String>)fieldValue; break;
			case 32: this.fechaPactadaDeEntrega = (System.String)fieldValue; break;
			case 33: this.altoEnCm = (System.Nullable<System.Double>)fieldValue; break;
			case 34: this.anchoEnCm = (System.Nullable<System.Double>)fieldValue; break;
			case 35: this.largoEnCm = (System.Nullable<System.Double>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
