// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Integracion.Esquemas.Referencias
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Direccion : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""Direccion"",""namespace"":""Integracion.Esquemas.Referencias"",""fields"":[{""name"":""abreviaturaProvincia"",""default"":null,""type"":[""null"",""string""]},{""name"":""calle"",""default"":null,""type"":[""null"",""string""]},{""name"":""codigoDeDireccion"",""default"":null,""type"":[""null"",""string""]},{""name"":""codigoCiudad"",""default"":null,""type"":[""null"",""string""]},{""name"":""codigoPostal"",""default"":null,""type"":[""null"",""string""]},{""name"":""nombreProvincia"",""default"":null,""type"":[""null"",""string""]},{""name"":""numero"",""default"":null,""type"":[""null"",""string""]},{""name"":""telefono"",""default"":null,""type"":[""null"",""string""]},{""name"":""codigoISOProvincia"",""doc"":""segun ISO -3166-2 (https://es.wikipedia.org/wiki/ISO_3166-2:AR)"",""default"":null,""type"":[""null"",""string""]},{""name"":""codigoISOPais"",""doc"":""segun ISO 3166-1 alpha-2 (https://es.wikipedia.org/wiki/ISO_3166-1#Tabla_de_c.C3.B3digos_alfa-2_asignados_o_reservados)"",""default"":null,""type"":[""null"",""string""]},{""name"":""localidad"",""default"":null,""type"":[""null"",""string""]},{""name"":""componentesDeDireccion"",""default"":null,""type"":[""null"",{""type"":""map"",""values"":""string""}]},{""name"":""coordenadas"",""default"":null,""type"":[""null"",{""type"":""record"",""name"":""GeoReferencia"",""namespace"":""Integracion.Esquemas.Referencias"",""fields"":[{""name"":""latitud"",""default"":null,""type"":[""null"",""double""]},{""name"":""longitud"",""default"":null,""type"":[""null"",""double""]},{""name"":""altura"",""default"":null,""type"":[""null"",""double""]}]}]}]}");
		private string _abreviaturaProvincia;
		private string _calle;
		private string _codigoDeDireccion;
		private string _codigoCiudad;
		private string _codigoPostal;
		private string _nombreProvincia;
		private string _numero;
		private string _telefono;
		/// <summary>
		/// segun ISO -3166-2 (https://es.wikipedia.org/wiki/ISO_3166-2:AR)
		/// </summary>
		private string _codigoISOProvincia;
		/// <summary>
		/// segun ISO 3166-1 alpha-2 (https://es.wikipedia.org/wiki/ISO_3166-1#Tabla_de_c.C3.B3digos_alfa-2_asignados_o_reservados)
		/// </summary>
		private string _codigoISOPais;
		private string _localidad;
		private IDictionary<string,System.String> _componentesDeDireccion;
		private Integracion.Esquemas.Referencias.GeoReferencia _coordenadas;
		public virtual Schema Schema
		{
			get
			{
				return Direccion._SCHEMA;
			}
		}
		public string abreviaturaProvincia
		{
			get
			{
				return this._abreviaturaProvincia;
			}
			set
			{
				this._abreviaturaProvincia = value;
			}
		}
		public string calle
		{
			get
			{
				return this._calle;
			}
			set
			{
				this._calle = value;
			}
		}
		public string codigoDeDireccion
		{
			get
			{
				return this._codigoDeDireccion;
			}
			set
			{
				this._codigoDeDireccion = value;
			}
		}
		public string codigoCiudad
		{
			get
			{
				return this._codigoCiudad;
			}
			set
			{
				this._codigoCiudad = value;
			}
		}
		public string codigoPostal
		{
			get
			{
				return this._codigoPostal;
			}
			set
			{
				this._codigoPostal = value;
			}
		}
		public string nombreProvincia
		{
			get
			{
				return this._nombreProvincia;
			}
			set
			{
				this._nombreProvincia = value;
			}
		}
		public string numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				this._numero = value;
			}
		}
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				this._telefono = value;
			}
		}
		/// <summary>
		/// segun ISO -3166-2 (https://es.wikipedia.org/wiki/ISO_3166-2:AR)
		/// </summary>
		public string codigoISOProvincia
		{
			get
			{
				return this._codigoISOProvincia;
			}
			set
			{
				this._codigoISOProvincia = value;
			}
		}
		/// <summary>
		/// segun ISO 3166-1 alpha-2 (https://es.wikipedia.org/wiki/ISO_3166-1#Tabla_de_c.C3.B3digos_alfa-2_asignados_o_reservados)
		/// </summary>
		public string codigoISOPais
		{
			get
			{
				return this._codigoISOPais;
			}
			set
			{
				this._codigoISOPais = value;
			}
		}
		public string localidad
		{
			get
			{
				return this._localidad;
			}
			set
			{
				this._localidad = value;
			}
		}
		public IDictionary<string,System.String> componentesDeDireccion
		{
			get
			{
				return this._componentesDeDireccion;
			}
			set
			{
				this._componentesDeDireccion = value;
			}
		}
		public Integracion.Esquemas.Referencias.GeoReferencia coordenadas
		{
			get
			{
				return this._coordenadas;
			}
			set
			{
				this._coordenadas = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.abreviaturaProvincia;
			case 1: return this.calle;
			case 2: return this.codigoDeDireccion;
			case 3: return this.codigoCiudad;
			case 4: return this.codigoPostal;
			case 5: return this.nombreProvincia;
			case 6: return this.numero;
			case 7: return this.telefono;
			case 8: return this.codigoISOProvincia;
			case 9: return this.codigoISOPais;
			case 10: return this.localidad;
			case 11: return this.componentesDeDireccion;
			case 12: return this.coordenadas;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.abreviaturaProvincia = (System.String)fieldValue; break;
			case 1: this.calle = (System.String)fieldValue; break;
			case 2: this.codigoDeDireccion = (System.String)fieldValue; break;
			case 3: this.codigoCiudad = (System.String)fieldValue; break;
			case 4: this.codigoPostal = (System.String)fieldValue; break;
			case 5: this.nombreProvincia = (System.String)fieldValue; break;
			case 6: this.numero = (System.String)fieldValue; break;
			case 7: this.telefono = (System.String)fieldValue; break;
			case 8: this.codigoISOProvincia = (System.String)fieldValue; break;
			case 9: this.codigoISOPais = (System.String)fieldValue; break;
			case 10: this.localidad = (System.String)fieldValue; break;
			case 11: this.componentesDeDireccion = (IDictionary<string,System.String>)fieldValue; break;
			case 12: this.coordenadas = (Integracion.Esquemas.Referencias.GeoReferencia)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
