// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Integracion.Esquemas.Referencias
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class LugarDeRetiroEntrega : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"LugarDeRetiroEntrega\",\"namespace\":\"Integracion.Esquemas." +
				"Referencias\",\"fields\":[{\"name\":\"datosSucursal\",\"default\":null,\"type\":[\"null\",{\"t" +
				"ype\":\"record\",\"name\":\"DatosSucursal\",\"namespace\":\"Integracion.Esquemas.Referenci" +
				"as\",\"fields\":[{\"name\":\"codigo\",\"type\":\"string\"},{\"name\":\"nombre\",\"default\":null," +
				"\"type\":[\"null\",\"string\"]},{\"name\":\"id\",\"type\":\"string\"}]}]},{\"name\":\"domicilio\"," +
				"\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Direccion\",\"namespace\":\"I" +
				"ntegracion.Esquemas.Referencias\",\"fields\":[{\"name\":\"abreviaturaProvincia\",\"defau" +
				"lt\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"calle\",\"default\":null,\"type\":[\"null\"" +
				",\"string\"]},{\"name\":\"codigoDeDireccion\",\"default\":null,\"type\":[\"null\",\"string\"]}" +
				",{\"name\":\"codigoCiudad\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"codigo" +
				"Postal\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"nombreProvincia\",\"defa" +
				"ult\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"numero\",\"default\":null,\"type\":[\"nul" +
				"l\",\"string\"]},{\"name\":\"telefono\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name" +
				"\":\"codigoISOProvincia\",\"doc\":\"segun ISO -3166-2 (https://es.wikipedia.org/wiki/I" +
				"SO_3166-2:AR)\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"codigoISOPais\"," +
				"\"doc\":\"segun ISO 3166-1 alpha-2 (https://es.wikipedia.org/wiki/ISO_3166-1#Tabla_" +
				"de_c.C3.B3digos_alfa-2_asignados_o_reservados)\",\"default\":null,\"type\":[\"null\",\"s" +
				"tring\"]},{\"name\":\"localidad\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"c" +
				"omponentesDeDireccion\",\"default\":null,\"type\":[\"null\",{\"type\":\"map\",\"values\":\"str" +
				"ing\"}]},{\"name\":\"coordenadas\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"na" +
				"me\":\"GeoReferencia\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"fields\":[{\"n" +
				"ame\":\"latitud\",\"default\":null,\"type\":[\"null\",\"double\"]},{\"name\":\"longitud\",\"defa" +
				"ult\":null,\"type\":[\"null\",\"double\"]},{\"name\":\"altura\",\"default\":null,\"type\":[\"nul" +
				"l\",\"double\"]}]}]}]}]}]}");
		private Integracion.Esquemas.Referencias.DatosSucursal _datosSucursal;
		private Integracion.Esquemas.Referencias.Direccion _domicilio;
		public virtual Schema Schema
		{
			get
			{
				return LugarDeRetiroEntrega._SCHEMA;
			}
		}
		public Integracion.Esquemas.Referencias.DatosSucursal datosSucursal
		{
			get
			{
				return this._datosSucursal;
			}
			set
			{
				this._datosSucursal = value;
			}
		}
		public Integracion.Esquemas.Referencias.Direccion domicilio
		{
			get
			{
				return this._domicilio;
			}
			set
			{
				this._domicilio = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.datosSucursal;
			case 1: return this.domicilio;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.datosSucursal = (Integracion.Esquemas.Referencias.DatosSucursal)fieldValue; break;
			case 1: this.domicilio = (Integracion.Esquemas.Referencias.Direccion)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
