// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Integracion.Esquemas.Trazas
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Admision : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""Admision"",""namespace"":""Integracion.Esquemas.Trazas"",""fields"":[{""name"":""timestamp"",""type"":""string""},{""name"":""remitente"",""type"":""string""},{""name"":""numeroDeOrden"",""type"":""string""},{""name"":""traza"",""type"":{""type"":""record"",""name"":""Traza"",""namespace"":""Integracion.Esquemas.Trazas"",""fields"":[{""name"":""codigoDeEnvio"",""type"":""string""},{""name"":""nombre"",""default"":null,""type"":[""null"",""string""]},{""name"":""cuando"",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}},{""name"":""codigoDeContratoInterno"",""type"":""string""},{""name"":""estadoDelEnvio"",""default"":null,""type"":[""null"",""string""]},{""name"":""cicloDelEnvio"",""default"":null,""type"":[""null"",""string""]},{""name"":""operador"",""default"":null,""type"":[""null"",""string""]},{""name"":""estadoDeLaRendicion"",""default"":null,""type"":[""null"",""string""]},{""name"":""comentario"",""default"":null,""type"":[""null"",""string""]},{""name"":""sucursalAsociadaAlEvento"",""default"":null,""type"":[""null"",{""type"":""record"",""name"":""DatosSucursal"",""namespace"":""Integracion.Esquemas.Referencias"",""fields"":[{""name"":""codigo"",""type"":""string""},{""name"":""nombre"",""default"":null,""type"":[""null"",""string""]},{""name"":""id"",""type"":""string""}]}]}]}},{""name"":""donde"",""type"":""Integracion.Esquemas.Referencias.DatosSucursal""}]}");
		private string _timestamp;
		private string _remitente;
		private string _numeroDeOrden;
		private Integracion.Esquemas.Trazas.Traza _traza;
		private Integracion.Esquemas.Referencias.DatosSucursal _donde;
		public virtual Schema Schema
		{
			get
			{
				return Admision._SCHEMA;
			}
		}
		public string timestamp
		{
			get
			{
				return this._timestamp;
			}
			set
			{
				this._timestamp = value;
			}
		}
		public string remitente
		{
			get
			{
				return this._remitente;
			}
			set
			{
				this._remitente = value;
			}
		}
		public string numeroDeOrden
		{
			get
			{
				return this._numeroDeOrden;
			}
			set
			{
				this._numeroDeOrden = value;
			}
		}
		public Integracion.Esquemas.Trazas.Traza traza
		{
			get
			{
				return this._traza;
			}
			set
			{
				this._traza = value;
			}
		}
		public Integracion.Esquemas.Referencias.DatosSucursal donde
		{
			get
			{
				return this._donde;
			}
			set
			{
				this._donde = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.timestamp;
			case 1: return this.remitente;
			case 2: return this.numeroDeOrden;
			case 3: return this.traza;
			case 4: return this.donde;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.timestamp = (System.String)fieldValue; break;
			case 1: this.remitente = (System.String)fieldValue; break;
			case 2: this.numeroDeOrden = (System.String)fieldValue; break;
			case 3: this.traza = (Integracion.Esquemas.Trazas.Traza)fieldValue; break;
			case 4: this.donde = (Integracion.Esquemas.Referencias.DatosSucursal)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
