// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Integracion.Esquemas.Trazas
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Alta : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Alta\",\"namespace\":\"Integracion.Esquemas.Trazas\",\"aliases" +
				"\":[\"AltaManual\",\"AltaAutomatica\",\"AltaRemota\",\"AltaConAnomalias\",\"AltaDeExcedent" +
				"e\"],\"fields\":[{\"name\":\"timestamp\",\"type\":\"string\"},{\"name\":\"remitente\",\"type\":\"s" +
				"tring\"},{\"name\":\"numeroDeOrden\",\"type\":\"string\"},{\"name\":\"traza\",\"type\":{\"type\":" +
				"\"record\",\"name\":\"Traza\",\"namespace\":\"Integracion.Esquemas.Trazas\",\"fields\":[{\"na" +
				"me\":\"codigoDeEnvio\",\"type\":\"string\"},{\"name\":\"nombre\",\"default\":null,\"type\":[\"nu" +
				"ll\",\"string\"]},{\"name\":\"cuando\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-m" +
				"illis\"}},{\"name\":\"codigoDeContratoInterno\",\"type\":\"string\"},{\"name\":\"estadoDelEn" +
				"vio\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"cicloDelEnvio\",\"default\":" +
				"null,\"type\":[\"null\",\"string\"]},{\"name\":\"operador\",\"default\":null,\"type\":[\"null\"," +
				"\"string\"]},{\"name\":\"estadoDeLaRendicion\",\"default\":null,\"type\":[\"null\",\"string\"]" +
				"},{\"name\":\"comentario\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"sucursa" +
				"lAsociadaAlEvento\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"DatosS" +
				"ucursal\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"fields\":[{\"name\":\"codig" +
				"o\",\"type\":\"string\"},{\"name\":\"nombre\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"" +
				"name\":\"id\",\"type\":\"string\"}]}]}]}},{\"name\":\"envio\",\"type\":{\"type\":\"record\",\"name" +
				"\":\"DetalleDeEnvio\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"fields\":[{\"na" +
				"me\":\"fechaDeRecibo\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"informaTar" +
				"ifa\",\"type\":\"boolean\"},{\"name\":\"lote\",\"default\":null,\"type\":[\"null\",\"string\"]},{" +
				"\"name\":\"numeroDeEnvio\",\"type\":\"string\"},{\"name\":\"numeroDeRecibo\",\"default\":null," +
				"\"type\":[\"null\",\"string\"]},{\"name\":\"numeroInformeDeRendicion\",\"default\":null,\"typ" +
				"e\":[\"null\",\"string\"]},{\"name\":\"peso\",\"default\":null,\"type\":[\"null\",\"float\"]},{\"n" +
				"ame\":\"pesoAforado\",\"default\":null,\"type\":[\"null\",\"float\"]},{\"name\":\"valorDeclara" +
				"do\",\"default\":null,\"type\":[\"null\",\"float\"]},{\"name\":\"valorACobrar\",\"default\":nul" +
				"l,\"type\":[\"null\",\"float\"]},{\"name\":\"volumen\",\"default\":null,\"type\":[\"null\",\"floa" +
				"t\"]},{\"name\":\"origen\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Lug" +
				"arDeRetiroEntrega\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"fields\":[{\"na" +
				"me\":\"datosSucursal\",\"default\":null,\"type\":[\"null\",\"DatosSucursal\"]},{\"name\":\"dom" +
				"icilio\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Direccion\",\"names" +
				"pace\":\"Integracion.Esquemas.Referencias\",\"fields\":[{\"name\":\"abreviaturaProvincia" +
				"\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"calle\",\"default\":null,\"type\"" +
				":[\"null\",\"string\"]},{\"name\":\"codigoDeDireccion\",\"default\":null,\"type\":[\"null\",\"s" +
				"tring\"]},{\"name\":\"codigoCiudad\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\"" +
				":\"codigoPostal\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"nombreProvinci" +
				"a\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"numero\",\"default\":null,\"typ" +
				"e\":[\"null\",\"string\"]},{\"name\":\"telefono\",\"default\":null,\"type\":[\"null\",\"string\"]" +
				"},{\"name\":\"codigoISOProvincia\",\"doc\":\"segun ISO -3166-2 (https://es.wikipedia.or" +
				"g/wiki/ISO_3166-2:AR)\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"codigoI" +
				"SOPais\",\"doc\":\"segun ISO 3166-1 alpha-2 (https://es.wikipedia.org/wiki/ISO_3166-" +
				"1#Tabla_de_c.C3.B3digos_alfa-2_asignados_o_reservados)\",\"default\":null,\"type\":[\"" +
				"null\",\"string\"]},{\"name\":\"localidad\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"" +
				"name\":\"componentesDeDireccion\",\"default\":null,\"type\":[\"null\",{\"type\":\"map\",\"valu" +
				"es\":\"string\"}]},{\"name\":\"coordenadas\",\"default\":null,\"type\":[\"null\",{\"type\":\"rec" +
				"ord\",\"name\":\"GeoReferencia\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"fiel" +
				"ds\":[{\"name\":\"latitud\",\"default\":null,\"type\":[\"null\",\"double\"]},{\"name\":\"longitu" +
				"d\",\"default\":null,\"type\":[\"null\",\"double\"]},{\"name\":\"altura\",\"default\":null,\"typ" +
				"e\":[\"null\",\"double\"]}]}]}]}]}]}]},{\"name\":\"sucursalOrigen\",\"default\":null,\"type\"" +
				":[\"null\",\"LugarDeRetiroEntrega\"]},{\"name\":\"destino\",\"type\":\"LugarDeRetiroEntrega" +
				"\"},{\"name\":\"sucursalDestino\",\"default\":null,\"type\":[\"null\",\"LugarDeRetiroEntrega" +
				"\"]},{\"name\":\"categoriaDeFacturacion\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"" +
				"name\":\"centroDeCostosDelCliente\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name" +
				"\":\"estado\",\"type\":\"string\"},{\"name\":\"codigoDeContratoInterno\",\"type\":\"string\"},{" +
				"\"name\":\"fechaInformeDeRendicion\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name" +
				"\":\"fechaAltaEnvio\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"ordenDeComp" +
				"raCliente\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"tarifa\",\"default\":n" +
				"ull,\"type\":[\"null\",\"double\"]},{\"name\":\"componentes\",\"type\":{\"type\":\"array\",\"item" +
				"s\":{\"type\":\"record\",\"name\":\"DatosPersonales\",\"namespace\":\"Integracion.Esquemas.R" +
				"eferencias\",\"fields\":[{\"name\":\"numeroDeDocumento\",\"default\":null,\"type\":[\"null\"," +
				"\"string\"]},{\"name\":\"nombreCompleto\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"n" +
				"ame\":\"idInternoDelCliente\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"eMa" +
				"il\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"telefonos\",\"default\":null," +
				"\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Telefono\",\"names" +
				"pace\":\"Integracion.Esquemas.Referencias\",\"fields\":[{\"name\":\"tipo\",\"type\":{\"type\"" +
				":\"enum\",\"name\":\"TipoDeTelefono\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"" +
				"symbols\":[\"trabajo\",\"celular\",\"casa\",\"otro\"]}},{\"name\":\"numero\",\"type\":\"string\"}" +
				"]}}]},{\"name\":\"agrupador\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"tipo" +
				"DeDocumento\",\"type\":{\"type\":\"enum\",\"name\":\"TipoDeDocumento\",\"namespace\":\"Integra" +
				"cion.Esquemas.Referencias\",\"symbols\":[\"undefined\",\"DNI\",\"CUIT\",\"CUIL\"]}}]}}},{\"n" +
				"ame\":\"destinatario\",\"default\":null,\"type\":[\"null\",\"DatosPersonales\"]},{\"name\":\"r" +
				"emitente\",\"default\":null,\"type\":[\"null\",\"DatosPersonales\"]},{\"name\":\"cantidadDeB" +
				"ultos\",\"default\":null,\"type\":[\"null\",\"int\"]},{\"name\":\"fechaProbableDeEntrega\",\"d" +
				"efault\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"observaciones\",\"default\":null,\"t" +
				"ype\":[\"null\",\"string\"]},{\"name\":\"numeroDeRemito\",\"default\":null,\"type\":[\"null\",\"" +
				"string\"]},{\"name\":\"numeroDeSeguimientoDelCliente\",\"default\":null,\"type\":[\"null\"," +
				"\"string\"]},{\"name\":\"datosAdicionales\",\"default\":null,\"type\":[\"null\",{\"type\":\"map" +
				"\",\"values\":\"string\"}]},{\"name\":\"fechaPactadaDeEntrega\",\"default\":null,\"type\":[\"n" +
				"ull\",\"string\"]},{\"name\":\"altoEnCm\",\"default\":null,\"type\":[\"null\",\"double\"]},{\"na" +
				"me\":\"anchoEnCm\",\"default\":null,\"type\":[\"null\",\"double\"]},{\"name\":\"largoEnCm\",\"de" +
				"fault\":null,\"type\":[\"null\",\"double\"]}]}},{\"name\":\"contrato\",\"type\":{\"type\":\"reco" +
				"rd\",\"name\":\"Contrato\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"fields\":[{" +
				"\"name\":\"codigoDeContratoInterno\",\"type\":\"string\"},{\"name\":\"descripcion\",\"default" +
				"\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"estaActivo\",\"type\":\"boolean\"},{\"name\":" +
				"\"tipoDeServicio\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"codigoDeDirec" +
				"cion\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"codigoDeClienteInterno\"," +
				"\"type\":\"string\"},{\"name\":\"vigenciaDesde\",\"default\":null,\"type\":[\"null\",\"string\"]" +
				"},{\"name\":\"vigenciaHasta\",\"default\":null,\"type\":[\"null\",\"string\"]}]}}]}");
		private string _timestamp;
		private string _remitente;
		private string _numeroDeOrden;
		private Integracion.Esquemas.Trazas.Traza _traza;
		private Integracion.Esquemas.Referencias.DetalleDeEnvio _envio;
		private Integracion.Esquemas.Referencias.Contrato _contrato;
		public virtual Schema Schema
		{
			get
			{
				return Alta._SCHEMA;
			}
		}
		public string timestamp
		{
			get
			{
				return this._timestamp;
			}
			set
			{
				this._timestamp = value;
			}
		}
		public string remitente
		{
			get
			{
				return this._remitente;
			}
			set
			{
				this._remitente = value;
			}
		}
		public string numeroDeOrden
		{
			get
			{
				return this._numeroDeOrden;
			}
			set
			{
				this._numeroDeOrden = value;
			}
		}
		public Integracion.Esquemas.Trazas.Traza traza
		{
			get
			{
				return this._traza;
			}
			set
			{
				this._traza = value;
			}
		}
		public Integracion.Esquemas.Referencias.DetalleDeEnvio envio
		{
			get
			{
				return this._envio;
			}
			set
			{
				this._envio = value;
			}
		}
		public Integracion.Esquemas.Referencias.Contrato contrato
		{
			get
			{
				return this._contrato;
			}
			set
			{
				this._contrato = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.timestamp;
			case 1: return this.remitente;
			case 2: return this.numeroDeOrden;
			case 3: return this.traza;
			case 4: return this.envio;
			case 5: return this.contrato;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.timestamp = (System.String)fieldValue; break;
			case 1: this.remitente = (System.String)fieldValue; break;
			case 2: this.numeroDeOrden = (System.String)fieldValue; break;
			case 3: this.traza = (Integracion.Esquemas.Trazas.Traza)fieldValue; break;
			case 4: this.envio = (Integracion.Esquemas.Referencias.DetalleDeEnvio)fieldValue; break;
			case 5: this.contrato = (Integracion.Esquemas.Referencias.Contrato)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
