// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Integracion.Esquemas.Trazas
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public abstract class EsquemasProtocol : Avro.Specific.ISpecificProtocol
	{
		private static readonly Avro.Protocol protocol = Avro.Protocol.Parse("{\"protocol\":\"EsquemasProtocol\",\"namespace\":\"Integracion.Esquemas.Trazas\",\"types\":" +
				"[{\"type\":\"record\",\"name\":\"Contrato\",\"namespace\":\"Integracion.Esquemas.Referencia" +
				"s\",\"fields\":[{\"name\":\"codigoDeContratoInterno\",\"type\":\"string\"},{\"name\":\"descrip" +
				"cion\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"estaActivo\",\"type\":\"bool" +
				"ean\"},{\"name\":\"tipoDeServicio\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":" +
				"\"codigoDeDireccion\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"codigoDeCl" +
				"ienteInterno\",\"type\":\"string\"},{\"name\":\"vigenciaDesde\",\"default\":null,\"type\":[\"n" +
				"ull\",\"string\"]},{\"name\":\"vigenciaHasta\",\"default\":null,\"type\":[\"null\",\"string\"]}" +
				"]},{\"type\":\"record\",\"name\":\"DatosPersonales\",\"namespace\":\"Integracion.Esquemas.R" +
				"eferencias\",\"fields\":[{\"name\":\"numeroDeDocumento\",\"default\":null,\"type\":[\"null\"," +
				"\"string\"]},{\"name\":\"nombreCompleto\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"n" +
				"ame\":\"idInternoDelCliente\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"eMa" +
				"il\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"telefonos\",\"default\":null," +
				"\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Telefono\",\"names" +
				"pace\":\"Integracion.Esquemas.Referencias\",\"fields\":[{\"name\":\"tipo\",\"type\":{\"type\"" +
				":\"enum\",\"name\":\"TipoDeTelefono\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"" +
				"symbols\":[\"trabajo\",\"celular\",\"casa\",\"otro\"]}},{\"name\":\"numero\",\"type\":\"string\"}" +
				"]}}]},{\"name\":\"agrupador\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"tipo" +
				"DeDocumento\",\"type\":{\"type\":\"enum\",\"name\":\"TipoDeDocumento\",\"namespace\":\"Integra" +
				"cion.Esquemas.Referencias\",\"symbols\":[\"undefined\",\"DNI\",\"CUIT\",\"CUIL\"]}}]},{\"typ" +
				"e\":\"record\",\"name\":\"DatosSucursal\",\"namespace\":\"Integracion.Esquemas.Referencias" +
				"\",\"fields\":[{\"name\":\"codigo\",\"type\":\"string\"},{\"name\":\"nombre\",\"default\":null,\"t" +
				"ype\":[\"null\",\"string\"]},{\"name\":\"id\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":" +
				"\"DetalleDeEnvio\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"fields\":[{\"name" +
				"\":\"fechaDeRecibo\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"informaTarif" +
				"a\",\"type\":\"boolean\"},{\"name\":\"lote\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"n" +
				"ame\":\"numeroDeEnvio\",\"type\":\"string\"},{\"name\":\"numeroDeRecibo\",\"default\":null,\"t" +
				"ype\":[\"null\",\"string\"]},{\"name\":\"numeroInformeDeRendicion\",\"default\":null,\"type\"" +
				":[\"null\",\"string\"]},{\"name\":\"peso\",\"default\":null,\"type\":[\"null\",\"float\"]},{\"nam" +
				"e\":\"pesoAforado\",\"default\":null,\"type\":[\"null\",\"float\"]},{\"name\":\"valorDeclarado" +
				"\",\"default\":null,\"type\":[\"null\",\"float\"]},{\"name\":\"valorACobrar\",\"default\":null," +
				"\"type\":[\"null\",\"float\"]},{\"name\":\"volumen\",\"default\":null,\"type\":[\"null\",\"float\"" +
				"]},{\"name\":\"origen\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Lugar" +
				"DeRetiroEntrega\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"fields\":[{\"name" +
				"\":\"datosSucursal\",\"default\":null,\"type\":[\"null\",\"DatosSucursal\"]},{\"name\":\"domic" +
				"ilio\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Direccion\",\"namespa" +
				"ce\":\"Integracion.Esquemas.Referencias\",\"fields\":[{\"name\":\"abreviaturaProvincia\"," +
				"\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"calle\",\"default\":null,\"type\":[" +
				"\"null\",\"string\"]},{\"name\":\"codigoDeDireccion\",\"default\":null,\"type\":[\"null\",\"str" +
				"ing\"]},{\"name\":\"codigoCiudad\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"" +
				"codigoPostal\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"nombreProvincia\"" +
				",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"numero\",\"default\":null,\"type\"" +
				":[\"null\",\"string\"]},{\"name\":\"telefono\",\"default\":null,\"type\":[\"null\",\"string\"]}," +
				"{\"name\":\"codigoISOProvincia\",\"doc\":\"segun ISO -3166-2 (https://es.wikipedia.org/" +
				"wiki/ISO_3166-2:AR)\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"codigoISO" +
				"Pais\",\"doc\":\"segun ISO 3166-1 alpha-2 (https://es.wikipedia.org/wiki/ISO_3166-1#" +
				"Tabla_de_c.C3.B3digos_alfa-2_asignados_o_reservados)\",\"default\":null,\"type\":[\"nu" +
				"ll\",\"string\"]},{\"name\":\"localidad\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"na" +
				"me\":\"componentesDeDireccion\",\"default\":null,\"type\":[\"null\",{\"type\":\"map\",\"values" +
				"\":\"string\"}]},{\"name\":\"coordenadas\",\"default\":null,\"type\":[\"null\",{\"type\":\"recor" +
				"d\",\"name\":\"GeoReferencia\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"fields" +
				"\":[{\"name\":\"latitud\",\"default\":null,\"type\":[\"null\",\"double\"]},{\"name\":\"longitud\"" +
				",\"default\":null,\"type\":[\"null\",\"double\"]},{\"name\":\"altura\",\"default\":null,\"type\"" +
				":[\"null\",\"double\"]}]}]}]}]}]}]},{\"name\":\"sucursalOrigen\",\"default\":null,\"type\":[" +
				"\"null\",\"LugarDeRetiroEntrega\"]},{\"name\":\"destino\",\"type\":\"LugarDeRetiroEntrega\"}" +
				",{\"name\":\"sucursalDestino\",\"default\":null,\"type\":[\"null\",\"LugarDeRetiroEntrega\"]" +
				"},{\"name\":\"categoriaDeFacturacion\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"na" +
				"me\":\"centroDeCostosDelCliente\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":" +
				"\"estado\",\"type\":\"string\"},{\"name\":\"codigoDeContratoInterno\",\"type\":\"string\"},{\"n" +
				"ame\":\"fechaInformeDeRendicion\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":" +
				"\"fechaAltaEnvio\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"ordenDeCompra" +
				"Cliente\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"tarifa\",\"default\":nul" +
				"l,\"type\":[\"null\",\"double\"]},{\"name\":\"componentes\",\"type\":{\"type\":\"array\",\"items\"" +
				":\"DatosPersonales\"}},{\"name\":\"destinatario\",\"default\":null,\"type\":[\"null\",\"Datos" +
				"Personales\"]},{\"name\":\"remitente\",\"default\":null,\"type\":[\"null\",\"DatosPersonales" +
				"\"]},{\"name\":\"cantidadDeBultos\",\"default\":null,\"type\":[\"null\",\"int\"]},{\"name\":\"fe" +
				"chaProbableDeEntrega\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"observac" +
				"iones\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"numeroDeRemito\",\"defaul" +
				"t\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"numeroDeSeguimientoDelCliente\",\"defau" +
				"lt\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"datosAdicionales\",\"default\":null,\"ty" +
				"pe\":[\"null\",{\"type\":\"map\",\"values\":\"string\"}]},{\"name\":\"fechaPactadaDeEntrega\",\"" +
				"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"altoEnCm\",\"default\":null,\"type\"" +
				":[\"null\",\"double\"]},{\"name\":\"anchoEnCm\",\"default\":null,\"type\":[\"null\",\"double\"]}" +
				",{\"name\":\"largoEnCm\",\"default\":null,\"type\":[\"null\",\"double\"]}]},{\"type\":\"record\"" +
				",\"name\":\"DetalleDeOrdenDeEnvio\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"" +
				"fields\":[{\"name\":\"numeroDeEnvio\",\"type\":\"string\"},{\"name\":\"remitenteInformado\",\"" +
				"default\":null,\"type\":[\"null\",\"DatosPersonales\"]},{\"name\":\"destinatarioInformado\"" +
				",\"type\":\"DatosPersonales\"},{\"name\":\"destinatarioAlternativo\",\"default\":null,\"typ" +
				"e\":[\"null\",\"DatosPersonales\"]},{\"name\":\"destinoInformado\",\"type\":\"LugarDeRetiroE" +
				"ntrega\"},{\"name\":\"origenInformado\",\"default\":null,\"type\":[\"null\",\"LugarDeRetiroE" +
				"ntrega\"]},{\"name\":\"codigoDeContratoInterno\",\"type\":\"string\"},{\"name\":\"tipoDeServ" +
				"icio\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"numeroDeRemito\",\"default" +
				"\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"remitosComplementarios\",\"default\":null" +
				",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"string\"}]},{\"name\":\"centroDeCostosDelCl" +
				"iente\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"categoriaDeProducto\",\"d" +
				"efault\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"categoriaDeFacturacion\",\"default" +
				"\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"valorACobrar\",\"default\":null,\"type\":[\"" +
				"null\",\"float\"]},{\"name\":\"fechaPactadaDeEntrega\",\"default\":null,\"type\":[\"null\",{\"" +
				"type\":\"record\",\"name\":\"FechaPactada\",\"namespace\":\"Integracion.Esquemas.Referenci" +
				"as\",\"fields\":[{\"name\":\"fecha\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"" +
				"horaDesde\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"horaHasta\",\"default" +
				"\":null,\"type\":[\"null\",\"string\"]}]}]},{\"name\":\"productoAEntregar\",\"default\":null," +
				"\"type\":[\"null\",\"string\"]},{\"name\":\"productoARetirar\",\"default\":null,\"type\":[\"nul" +
				"l\",\"string\"]},{\"name\":\"pagoDestino\",\"type\":{\"type\":\"enum\",\"name\":\"TipoPagoDestin" +
				"o\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"symbols\":[\"undefined\",\"P\",\"D\"" +
				"]}},{\"name\":\"sucursalDeDistribucion\",\"default\":null,\"type\":[\"null\",\"DatosSucursa" +
				"l\"]},{\"name\":\"sucursalCliente\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":" +
				"\"listaDePaquetes\",\"default\":null,\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":" +
				"\"record\",\"name\":\"DetalleDePaquete\",\"namespace\":\"Integracion.Esquemas.Referencias" +
				"\",\"fields\":[{\"name\":\"pesoEnKg\",\"default\":null,\"type\":[\"null\",\"float\"]},{\"name\":\"" +
				"altoEnCm\",\"default\":null,\"type\":[\"null\",\"float\"]},{\"name\":\"anchoEnCm\",\"default\":" +
				"null,\"type\":[\"null\",\"float\"]},{\"name\":\"largoEnCm\",\"default\":null,\"type\":[\"null\"," +
				"\"float\"]},{\"name\":\"descripcion\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\"" +
				":\"referenciasDelCliente\",\"default\":null,\"type\":[\"null\",{\"type\":\"map\",\"values\":\"s" +
				"tring\"}]},{\"name\":\"volumenEnCm3\",\"default\":null,\"type\":[\"null\",\"float\"]},{\"name\"" +
				":\"valorDeclaradoSinImpuesto\",\"default\":null,\"type\":[\"null\",\"float\"]},{\"name\":\"va" +
				"lorDeclaradoConImpuesto\",\"default\":null,\"type\":[\"null\",\"float\"]}]}}]}]},{\"type\":" +
				"\"enum\",\"name\":\"TipoDeEntrega\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"sy" +
				"mbols\":[\"undefined\",\"distribucion\",\"deliveryWindow\"]},{\"type\":\"record\",\"name\":\"T" +
				"raza\",\"namespace\":\"Integracion.Esquemas.Trazas\",\"fields\":[{\"name\":\"codigoDeEnvio" +
				"\",\"type\":\"string\"},{\"name\":\"nombre\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"n" +
				"ame\":\"cuando\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"" +
				"codigoDeContratoInterno\",\"type\":\"string\"},{\"name\":\"estadoDelEnvio\",\"default\":nul" +
				"l,\"type\":[\"null\",\"string\"]},{\"name\":\"cicloDelEnvio\",\"default\":null,\"type\":[\"null" +
				"\",\"string\"]},{\"name\":\"operador\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\"" +
				":\"estadoDeLaRendicion\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"comenta" +
				"rio\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"sucursalAsociadaAlEvento\"" +
				",\"default\":null,\"type\":[\"null\",\"Integracion.Esquemas.Referencias.DatosSucursal\"]" +
				"}]},{\"type\":\"record\",\"name\":\"Admision\",\"namespace\":\"Integracion.Esquemas.Trazas\"" +
				",\"fields\":[{\"name\":\"timestamp\",\"type\":\"string\"},{\"name\":\"remitente\",\"type\":\"stri" +
				"ng\"},{\"name\":\"numeroDeOrden\",\"type\":\"string\"},{\"name\":\"traza\",\"type\":\"Traza\"},{\"" +
				"name\":\"donde\",\"type\":\"Integracion.Esquemas.Referencias.DatosSucursal\"}]},{\"type\"" +
				":\"record\",\"name\":\"Alta\",\"namespace\":\"Integracion.Esquemas.Trazas\",\"aliases\":[\"Al" +
				"taManual\",\"AltaAutomatica\",\"AltaRemota\",\"AltaConAnomalias\",\"AltaDeExcedente\"],\"f" +
				"ields\":[{\"name\":\"timestamp\",\"type\":\"string\"},{\"name\":\"remitente\",\"type\":\"string\"" +
				"},{\"name\":\"numeroDeOrden\",\"type\":\"string\"},{\"name\":\"traza\",\"type\":\"Traza\"},{\"nam" +
				"e\":\"envio\",\"type\":\"Integracion.Esquemas.Referencias.DetalleDeEnvio\"},{\"name\":\"co" +
				"ntrato\",\"type\":\"Integracion.Esquemas.Referencias.Contrato\"}]},{\"type\":\"record\",\"" +
				"name\":\"ComienzoCustodiaEnSucursal\",\"namespace\":\"Integracion.Esquemas.Trazas\",\"fi" +
				"elds\":[{\"name\":\"timestamp\",\"type\":\"string\"},{\"name\":\"remitente\",\"type\":\"string\"}" +
				",{\"name\":\"numeroDeOrden\",\"type\":\"string\"},{\"name\":\"traza\",\"type\":\"Traza\"},{\"name" +
				"\":\"cantidadDeDiasDeLaFase\",\"type\":\"int\"},{\"name\":\"motivo\",\"default\":null,\"type\":" +
				"[\"null\",\"string\"]},{\"name\":\"submotivo\",\"default\":null,\"type\":[\"null\",\"string\"]}," +
				"{\"name\":\"sucursalDeCustodia\",\"default\":null,\"type\":[\"null\",\"Integracion.Esquemas" +
				".Referencias.DatosSucursal\"]}]},{\"type\":\"record\",\"name\":\"EliminarMarcaDeRescate\"" +
				",\"namespace\":\"Integracion.Esquemas.Trazas\",\"fields\":[{\"name\":\"timestamp\",\"type\":" +
				"\"string\"},{\"name\":\"remitente\",\"type\":\"string\"},{\"name\":\"numeroDeOrden\",\"type\":\"s" +
				"tring\"},{\"name\":\"traza\",\"type\":\"Traza\"}]},{\"type\":\"record\",\"name\":\"EnvioDesactiv" +
				"adoAutomaticamente\",\"namespace\":\"Integracion.Esquemas.Trazas\",\"fields\":[{\"name\":" +
				"\"timestamp\",\"type\":\"string\"},{\"name\":\"remitente\",\"type\":\"string\"},{\"name\":\"numer" +
				"oDeOrden\",\"type\":\"string\"},{\"name\":\"traza\",\"type\":\"Traza\"}]},{\"type\":\"record\",\"n" +
				"ame\":\"EnvioEntregado\",\"namespace\":\"Integracion.Esquemas.Trazas\",\"fields\":[{\"name" +
				"\":\"timestamp\",\"type\":\"string\"},{\"name\":\"remitente\",\"type\":\"string\"},{\"name\":\"num" +
				"eroDeOrden\",\"type\":\"string\"},{\"name\":\"traza\",\"type\":\"Traza\"},{\"name\":\"tipoDeEntr" +
				"ega\",\"type\":\"Integracion.Esquemas.Referencias.TipoDeEntrega\"}]},{\"type\":\"record\"" +
				",\"name\":\"FinCustodiaEnSucursal\",\"namespace\":\"Integracion.Esquemas.Trazas\",\"field" +
				"s\":[{\"name\":\"timestamp\",\"type\":\"string\"},{\"name\":\"remitente\",\"type\":\"string\"},{\"" +
				"name\":\"numeroDeOrden\",\"type\":\"string\"},{\"name\":\"traza\",\"type\":\"Traza\"},{\"name\":\"" +
				"cantidadDeDias\",\"type\":\"int\"},{\"name\":\"motivo\",\"default\":null,\"type\":[\"null\",\"st" +
				"ring\"]},{\"name\":\"submotivo\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"su" +
				"cursalDeDistribucion\",\"default\":null,\"type\":[\"null\",\"Integracion.Esquemas.Refere" +
				"ncias.DatosSucursal\"]}]},{\"type\":\"record\",\"name\":\"OrdenDeEnvioCreada\",\"namespace" +
				"\":\"Integracion.Esquemas.Trazas\",\"fields\":[{\"name\":\"timestamp\",\"type\":\"string\"},{" +
				"\"name\":\"remitente\",\"type\":\"string\"},{\"name\":\"numeroDeOrden\",\"type\":\"string\"},{\"n" +
				"ame\":\"traza\",\"type\":\"Traza\"},{\"name\":\"datosDeLaOrden\",\"type\":\"Integracion.Esquem" +
				"as.Referencias.DetalleDeOrdenDeEnvio\"},{\"name\":\"linking\",\"default\":null,\"type\":[" +
				"\"null\",{\"type\":\"map\",\"values\":\"string\"}]}]},{\"type\":\"record\",\"name\":\"Reactivacio" +
				"nDeBolsin\",\"namespace\":\"Integracion.Esquemas.Trazas\",\"fields\":[{\"name\":\"timestam" +
				"p\",\"type\":\"string\"},{\"name\":\"remitente\",\"type\":\"string\"},{\"name\":\"numeroDeOrden\"" +
				",\"type\":\"string\"},{\"name\":\"traza\",\"type\":\"Traza\"},{\"name\":\"sucursalOrigen\",\"type" +
				"\":\"Integracion.Esquemas.Referencias.DatosSucursal\"},{\"name\":\"sucursalDestino\",\"t" +
				"ype\":\"Integracion.Esquemas.Referencias.DatosSucursal\"}]},{\"type\":\"record\",\"name\"" +
				":\"Rescate\",\"namespace\":\"Integracion.Esquemas.Trazas\",\"fields\":[{\"name\":\"timestam" +
				"p\",\"type\":\"string\"},{\"name\":\"remitente\",\"type\":\"string\"},{\"name\":\"numeroDeOrden\"" +
				",\"type\":\"string\"},{\"name\":\"traza\",\"type\":\"Traza\"},{\"name\":\"numeroDeInformeDeRend" +
				"icion\",\"default\":null,\"type\":[\"null\",\"string\"]}]}],\"messages\":{}}");
		public Avro.Protocol Protocol
		{
			get
			{
				return protocol;
			}
		}
		public void Request(Avro.Specific.ICallbackRequestor requestor, string messageName, object[] args, object callback)
		{
			;
		}
	}
}
