// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Integracion.Esquemas.Trazas
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public abstract class EsquemasProtocol : Avro.Specific.ISpecificProtocol
	{
		private static readonly Avro.Protocol protocol = Avro.Protocol.Parse("{\"protocol\":\"EsquemasProtocol\",\"namespace\":\"Integracion.Esquemas.Trazas\",\"types\":" +
				"[{\"type\":\"record\",\"name\":\"Contrato\",\"namespace\":\"Integracion.Esquemas.Referencia" +
				"s\",\"fields\":[{\"name\":\"codigoDeContratoInterno\",\"type\":\"string\"},{\"name\":\"descrip" +
				"cion\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"estaActivo\",\"type\":\"bool" +
				"ean\"},{\"name\":\"tipoDeServicio\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":" +
				"\"codigoDeDireccion\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"codigoDeCl" +
				"ienteInterno\",\"type\":\"string\"},{\"name\":\"vigenciaDesde\",\"default\":null,\"type\":[\"n" +
				"ull\",\"string\"]},{\"name\":\"vigenciaHasta\",\"default\":null,\"type\":[\"null\",\"string\"]}" +
				"]},{\"type\":\"record\",\"name\":\"DatosPersonales\",\"namespace\":\"Integracion.Esquemas.R" +
				"eferencias\",\"fields\":[{\"name\":\"numeroDeDocumento\",\"default\":null,\"type\":[\"null\"," +
				"\"string\"]},{\"name\":\"nombreCompleto\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"n" +
				"ame\":\"idInternoDelCliente\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"eMa" +
				"il\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"telefonos\",\"default\":null," +
				"\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Telefono\",\"names" +
				"pace\":\"Integracion.Esquemas.Referencias\",\"fields\":[{\"name\":\"tipo\",\"type\":{\"type\"" +
				":\"enum\",\"name\":\"TipoDeTelefono\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"" +
				"symbols\":[\"trabajo\",\"celular\",\"casa\",\"otro\"]}},{\"name\":\"numero\",\"type\":\"string\"}" +
				"]}}]},{\"name\":\"agrupador\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"tipo" +
				"DeDocumento\",\"type\":{\"type\":\"enum\",\"name\":\"TipoDeDocumento\",\"namespace\":\"Integra" +
				"cion.Esquemas.Referencias\",\"symbols\":[\"undefined\",\"DNI\",\"CUIT\",\"CUIL\"]}}]},{\"typ" +
				"e\":\"record\",\"name\":\"DatosSucursal\",\"namespace\":\"Integracion.Esquemas.Referencias" +
				"\",\"fields\":[{\"name\":\"codigo\",\"type\":\"string\"},{\"name\":\"nombre\",\"default\":null,\"t" +
				"ype\":[\"null\",\"string\"]},{\"name\":\"id\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":" +
				"\"DetalleDeEnvio\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"fields\":[{\"name" +
				"\":\"fechaDeRecibo\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"informaTarif" +
				"a\",\"type\":\"boolean\"},{\"name\":\"lote\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"n" +
				"ame\":\"numeroDeEnvio\",\"type\":\"string\"},{\"name\":\"numeroDeRecibo\",\"default\":null,\"t" +
				"ype\":[\"null\",\"string\"]},{\"name\":\"numeroInformeDeRendicion\",\"default\":null,\"type\"" +
				":[\"null\",\"string\"]},{\"name\":\"peso\",\"default\":null,\"type\":[\"null\",\"float\"]},{\"nam" +
				"e\":\"pesoAforado\",\"default\":null,\"type\":[\"null\",\"float\"]},{\"name\":\"valorDeclarado" +
				"\",\"default\":null,\"type\":[\"null\",\"float\"]},{\"name\":\"valorACobrar\",\"default\":null," +
				"\"type\":[\"null\",\"float\"]},{\"name\":\"volumen\",\"default\":null,\"type\":[\"null\",\"float\"" +
				"]},{\"name\":\"origen\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Lugar" +
				"DeRetiroEntrega\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"fields\":[{\"name" +
				"\":\"datosSucursal\",\"default\":null,\"type\":[\"null\",\"DatosSucursal\"]},{\"name\":\"domic" +
				"ilio\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Direccion\",\"namespa" +
				"ce\":\"Integracion.Esquemas.Referencias\",\"fields\":[{\"name\":\"abreviaturaProvincia\"," +
				"\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"calle\",\"default\":null,\"type\":[" +
				"\"null\",\"string\"]},{\"name\":\"codigoDeDireccion\",\"default\":null,\"type\":[\"null\",\"str" +
				"ing\"]},{\"name\":\"codigoCiudad\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"" +
				"codigoPostal\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"nombreProvincia\"" +
				",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"numero\",\"default\":null,\"type\"" +
				":[\"null\",\"string\"]},{\"name\":\"telefono\",\"default\":null,\"type\":[\"null\",\"string\"]}," +
				"{\"name\":\"codigoISOProvincia\",\"doc\":\"segun ISO -3166-2 (https://es.wikipedia.org/" +
				"wiki/ISO_3166-2:AR)\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"codigoISO" +
				"Pais\",\"doc\":\"segun ISO 3166-1 alpha-2 (https://es.wikipedia.org/wiki/ISO_3166-1#" +
				"Tabla_de_c.C3.B3digos_alfa-2_asignados_o_reservados)\",\"default\":null,\"type\":[\"nu" +
				"ll\",\"string\"]},{\"name\":\"localidad\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"na" +
				"me\":\"componentesDeDireccion\",\"default\":null,\"type\":[\"null\",{\"type\":\"map\",\"values" +
				"\":\"string\"}]},{\"name\":\"coordenadas\",\"default\":null,\"type\":[\"null\",{\"type\":\"recor" +
				"d\",\"name\":\"GeoReferencia\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"fields" +
				"\":[{\"name\":\"latitud\",\"default\":null,\"type\":[\"null\",\"double\"]},{\"name\":\"longitud\"" +
				",\"default\":null,\"type\":[\"null\",\"double\"]},{\"name\":\"altura\",\"default\":null,\"type\"" +
				":[\"null\",\"double\"]}]}]}]}]}]}]},{\"name\":\"sucursalOrigen\",\"default\":null,\"type\":[" +
				"\"null\",\"LugarDeRetiroEntrega\"]},{\"name\":\"destino\",\"type\":\"LugarDeRetiroEntrega\"}" +
				",{\"name\":\"sucursalDestino\",\"default\":null,\"type\":[\"null\",\"LugarDeRetiroEntrega\"]" +
				"},{\"name\":\"categoriaDeFacturacion\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"na" +
				"me\":\"centroDeCostosDelCliente\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":" +
				"\"estado\",\"type\":\"string\"},{\"name\":\"codigoDeContratoInterno\",\"type\":\"string\"},{\"n" +
				"ame\":\"fechaInformeDeRendicion\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":" +
				"\"fechaAltaEnvio\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"ordenDeCompra" +
				"Cliente\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"tarifa\",\"default\":nul" +
				"l,\"type\":[\"null\",\"double\"]},{\"name\":\"componentes\",\"type\":{\"type\":\"array\",\"items\"" +
				":\"DatosPersonales\"}},{\"name\":\"destinatario\",\"default\":null,\"type\":[\"null\",\"Datos" +
				"Personales\"]},{\"name\":\"remitente\",\"default\":null,\"type\":[\"null\",\"DatosPersonales" +
				"\"]},{\"name\":\"cantidadDeBultos\",\"default\":null,\"type\":[\"null\",\"int\"]},{\"name\":\"fe" +
				"chaProbableDeEntrega\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"observac" +
				"iones\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"numeroDeRemito\",\"defaul" +
				"t\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"numeroDeSeguimientoDelCliente\",\"defau" +
				"lt\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"datosAdicionales\",\"default\":null,\"ty" +
				"pe\":[\"null\",{\"type\":\"map\",\"values\":\"string\"}]},{\"name\":\"fechaPactadaDeEntrega\",\"" +
				"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"altoEnCm\",\"default\":null,\"type\"" +
				":[\"null\",\"double\"]},{\"name\":\"anchoEnCm\",\"default\":null,\"type\":[\"null\",\"double\"]}" +
				",{\"name\":\"largoEnCm\",\"default\":null,\"type\":[\"null\",\"double\"]}]},{\"type\":\"enum\",\"" +
				"name\":\"TipoDeEntrega\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"symbols\":[" +
				"\"undefined\",\"distribucion\",\"deliveryWindow\"]},{\"type\":\"record\",\"name\":\"Traza\",\"n" +
				"amespace\":\"Integracion.Esquemas.Trazas\",\"fields\":[{\"name\":\"codigoDeEnvio\",\"type\"" +
				":\"string\"},{\"name\":\"nombre\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"cu" +
				"ando\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"codigoDe" +
				"ContratoInterno\",\"type\":\"string\"},{\"name\":\"estadoDelEnvio\",\"default\":null,\"type\"" +
				":[\"null\",\"string\"]},{\"name\":\"cicloDelEnvio\",\"default\":null,\"type\":[\"null\",\"strin" +
				"g\"]},{\"name\":\"operador\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"estado" +
				"DeLaRendicion\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"comentario\",\"de" +
				"fault\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"sucursalAsociadaAlEvento\",\"defaul" +
				"t\":null,\"type\":[\"null\",\"Integracion.Esquemas.Referencias.DatosSucursal\"]}]},{\"ty" +
				"pe\":\"record\",\"name\":\"Admision\",\"namespace\":\"Integracion.Esquemas.Trazas\",\"fields" +
				"\":[{\"name\":\"timestamp\",\"type\":\"string\"},{\"name\":\"remitente\",\"type\":\"string\"},{\"n" +
				"ame\":\"numeroDeOrden\",\"type\":\"string\"},{\"name\":\"traza\",\"type\":\"Traza\"},{\"name\":\"d" +
				"onde\",\"type\":\"Integracion.Esquemas.Referencias.DatosSucursal\"}]},{\"type\":\"record" +
				"\",\"name\":\"Alta\",\"namespace\":\"Integracion.Esquemas.Trazas\",\"aliases\":[\"AltaManual" +
				"\",\"AltaAutomatica\",\"AltaRemota\",\"AltaConAnomalias\",\"AltaDeExcedente\"],\"fields\":[" +
				"{\"name\":\"timestamp\",\"type\":\"string\"},{\"name\":\"remitente\",\"type\":\"string\"},{\"name" +
				"\":\"numeroDeOrden\",\"type\":\"string\"},{\"name\":\"traza\",\"type\":\"Traza\"},{\"name\":\"envi" +
				"o\",\"type\":\"Integracion.Esquemas.Referencias.DetalleDeEnvio\"},{\"name\":\"contrato\"," +
				"\"type\":\"Integracion.Esquemas.Referencias.Contrato\"}]},{\"type\":\"record\",\"name\":\"E" +
				"nvioEntregado\",\"namespace\":\"Integracion.Esquemas.Trazas\",\"fields\":[{\"name\":\"time" +
				"stamp\",\"type\":\"string\"},{\"name\":\"remitente\",\"type\":\"string\"},{\"name\":\"numeroDeOr" +
				"den\",\"type\":\"string\"},{\"name\":\"traza\",\"type\":\"Traza\"},{\"name\":\"tipoDeEntrega\",\"t" +
				"ype\":\"Integracion.Esquemas.Referencias.TipoDeEntrega\"}]}],\"messages\":{}}");
		public Avro.Protocol Protocol
		{
			get
			{
				return protocol;
			}
		}
		public void Request(Avro.Specific.ICallbackRequestor requestor, string messageName, object[] args, object callback)
		{
			;
		}
	}
}
