// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Integracion.Esquemas.Trazas
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Traza : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""Traza"",""namespace"":""Integracion.Esquemas.Trazas"",""fields"":[{""name"":""codigoDeEnvio"",""type"":""string""},{""name"":""nombre"",""default"":null,""type"":[""null"",""string""]},{""name"":""cuando"",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}},{""name"":""codigoDeContratoInterno"",""type"":""string""},{""name"":""estadoDelEnvio"",""default"":null,""type"":[""null"",""string""]},{""name"":""cicloDelEnvio"",""default"":null,""type"":[""null"",""string""]},{""name"":""operador"",""default"":null,""type"":[""null"",""string""]},{""name"":""estadoDeLaRendicion"",""default"":null,""type"":[""null"",""string""]},{""name"":""comentario"",""default"":null,""type"":[""null"",""string""]},{""name"":""sucursalAsociadaAlEvento"",""default"":null,""type"":[""null"",{""type"":""record"",""name"":""DatosSucursal"",""namespace"":""Integracion.Esquemas.Referencias"",""fields"":[{""name"":""codigo"",""type"":""string""},{""name"":""nombre"",""default"":null,""type"":[""null"",""string""]},{""name"":""id"",""type"":""string""}]}]}]}");
		private string _codigoDeEnvio;
		private string _nombre;
		private System.DateTime _cuando;
		private string _codigoDeContratoInterno;
		private string _estadoDelEnvio;
		private string _cicloDelEnvio;
		private string _operador;
		private string _estadoDeLaRendicion;
		private string _comentario;
		private Integracion.Esquemas.Referencias.DatosSucursal _sucursalAsociadaAlEvento;
		public virtual Schema Schema
		{
			get
			{
				return Traza._SCHEMA;
			}
		}
		public string codigoDeEnvio
		{
			get
			{
				return this._codigoDeEnvio;
			}
			set
			{
				this._codigoDeEnvio = value;
			}
		}
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		public System.DateTime cuando
		{
			get
			{
				return this._cuando;
			}
			set
			{
				this._cuando = value;
			}
		}
		public string codigoDeContratoInterno
		{
			get
			{
				return this._codigoDeContratoInterno;
			}
			set
			{
				this._codigoDeContratoInterno = value;
			}
		}
		public string estadoDelEnvio
		{
			get
			{
				return this._estadoDelEnvio;
			}
			set
			{
				this._estadoDelEnvio = value;
			}
		}
		public string cicloDelEnvio
		{
			get
			{
				return this._cicloDelEnvio;
			}
			set
			{
				this._cicloDelEnvio = value;
			}
		}
		public string operador
		{
			get
			{
				return this._operador;
			}
			set
			{
				this._operador = value;
			}
		}
		public string estadoDeLaRendicion
		{
			get
			{
				return this._estadoDeLaRendicion;
			}
			set
			{
				this._estadoDeLaRendicion = value;
			}
		}
		public string comentario
		{
			get
			{
				return this._comentario;
			}
			set
			{
				this._comentario = value;
			}
		}
		public Integracion.Esquemas.Referencias.DatosSucursal sucursalAsociadaAlEvento
		{
			get
			{
				return this._sucursalAsociadaAlEvento;
			}
			set
			{
				this._sucursalAsociadaAlEvento = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.codigoDeEnvio;
			case 1: return this.nombre;
			case 2: return this.cuando;
			case 3: return this.codigoDeContratoInterno;
			case 4: return this.estadoDelEnvio;
			case 5: return this.cicloDelEnvio;
			case 6: return this.operador;
			case 7: return this.estadoDeLaRendicion;
			case 8: return this.comentario;
			case 9: return this.sucursalAsociadaAlEvento;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.codigoDeEnvio = (System.String)fieldValue; break;
			case 1: this.nombre = (System.String)fieldValue; break;
			case 2: this.cuando = (System.DateTime)fieldValue; break;
			case 3: this.codigoDeContratoInterno = (System.String)fieldValue; break;
			case 4: this.estadoDelEnvio = (System.String)fieldValue; break;
			case 5: this.cicloDelEnvio = (System.String)fieldValue; break;
			case 6: this.operador = (System.String)fieldValue; break;
			case 7: this.estadoDeLaRendicion = (System.String)fieldValue; break;
			case 8: this.comentario = (System.String)fieldValue; break;
			case 9: this.sucursalAsociadaAlEvento = (Integracion.Esquemas.Referencias.DatosSucursal)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
