name: Publish Avro
on:
  push:
    branches:
      - main
    paths:
      - 'idl/**'
env:
  GITHUB_PROJECT_OWNER: Trazas # reemplace por su appname
  SOURCE_EVENTS_FILE_IDL: 'idl/EventosDeTraza.avdl' # archivo avdl remplace {Example}
jobs:
  avro: # genera los avro
    runs-on: ubuntu-latest
    steps:
      - uses: architecture-it/actions@avro
        with:
          file_idl: ${{ env.SOURCE_EVENTS_FILE_IDL }}
  Net: # publica la librería en nuget
    name: publish lib net
    needs: [avro]
    runs-on: ubuntu-latest
    steps:
      - uses: architecture-it/actions@avro-net
        with: 
          app_name: ${{ env.GITHUB_PROJECT_OWNER }}
          github_token: ${{ secrets.ARQUITECTURA_DEPLOY }}
          PackageVersion: 1.0.$GITHUB_RUN_NUMBER
  Golang: # publica las structs en integracion-schemas-event-go 
    name: publish lib go
    needs: [avro]
    runs-on: ubuntu-latest
    steps:
      - uses: architecture-it/actions@avro-go
        with: 
          app_name: ${{ env.GITHUB_PROJECT_OWNER }}
          github_token: ${{ secrets.ARQUITECTURA_DEPLOY }}
